LEDE.WebUI/Controllers/RatingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using LEDE.Domain.Abstract;
using LEDE.Domain.Concrete;
using LEDE.Domain.Entities;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;

namespace LEDE.WebUI.Controllers
{
    [Authorize(Roles="Faculty")]
    public class RatingController : Controller
    {
        private LEDE.Domain.Abstract.IRatingRepository db;
        private FacultyAccess AccessValidator; 

        public RatingController(LEDE.Domain.Abstract.IRatingRepository repo)
        {
            this.db = repo;
            this.AccessValidator = new FacultyAccess();
        }

        public PartialViewResult GetIndexData(int SelectedUserID, int ProgramCohortID)
        {
            ViewBag.ProgramCohortID = ProgramCohortID; 
            return PartialView(db.getTaskVersions(SelectedUserID, ProgramCohortID)); 
        }

        public ActionResult Index(bool? UploadVisible, int? VersID, int? userID, int? ProgramCohortID)
        {
            int FacultyID = Convert.ToInt32(User.Identity.GetUserId()); 
            RatingIndexModel model = db.getIndexModel(FacultyID, ProgramCohortID, userID);
            model.UploadVisible = UploadVisible ?? false;
            model.VersID = VersID;

            return View(model);
        }

        [HttpPost]
        public ActionResult Index(RatingIndexPost post)
        {
            int FacultyID = Convert.ToInt32(User.Identity.GetUserId()); 
            RatingIndexModel model = db.getIndexModel(FacultyID, post.SelectedCohortID, post.SelectedUserID);
            model.SelectedCohortID = post.SelectedCohortID ?? 1; //added by BB

            return View(model);
        }

        public ActionResult Download(int DocumentID)
        {            
            Document downloadDoc = db.findDocument((int)DocumentID);            
            FileManager.DownloadDocument(downloadDoc, HttpContext);             

            return RedirectToAction("Index");
        }

        public PartialViewResult Upload(int VersID, int SelectedUserID, string User, string TaskName, int Version, string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl; 
            ViewBag.Version = Version;
            ViewBag.SelectedUserID = SelectedUserID; 
            ViewBag.User = User;
            ViewBag.TaskName = TaskName; 
            return PartialView(VersID);
        }

        [HttpPost]
        public ActionResult Upload(HttpPostedFileBase file, int SelectedUserID, int VersID, string returnUrl)
        {
            
            if (file != null && file.ContentLength > 0)
            {
                Document feedbackUpload = new Document
                {
                    FileName = file.FileName,
                    FileSize = file.ContentLength.ToString(),
                    UploadDate = DateTime.Now,
                    Container = "user" + SelectedUserID
                };               
                
                db.saveFeedback(feedbackUpload, VersID);
                try
                {
                    FileManager.UploadDocument(feedbackUpload, file);
                    ViewBag.SuccessMessage = "Upload Successfull!";
                }
                catch
                {
                    ViewBag.SuccessMessage = "Upload Failed. Please Try Again.";
                }
            }
            else
            {
                ViewBag.SuccessMessage = "Upload Failed. Please attach a non-empty file";
            }

            if (returnUrl != null)
            {
                return Redirect(returnUrl + "&Message=" + ViewBag.SuccessMessage);
            }
            else
            {
                return RedirectToAction("Index");
            }
        }


        public ActionResult RateTask(int VersID)
        {
            RatingViewModel model = db.getRatingModel(VersID);
            return View(model);
        }

        public ActionResult Rate(int VersID, string Message = "")
        {
            try
            {
                AccessValidator.Validate(Int32.Parse(User.Identity.GetUserId()), VersID);
            }
            catch
            {
                ViewBag.InvalidAccessError = true;
                return View();
            }
            RatingViewModel model = db.getRatingModel(VersID);
            ViewBag.SuccessMessage = Message;
            return View(model);
        }

        [HttpPost]
        public ActionResult Rate(RatingViewModel post)
        {
            if (ModelState.IsValid)
            {
                db.saveCompleteRating(post);
                ViewBag.SuccessMessage = "Rating Saved Succesfully";
            }

            RatingViewModel model = db.getRatingModel(post.VersID);
            return View(model);

        }
        
        [HttpPost]
        public ActionResult Header(RatingViewModel post)
        {
            return RedirectToAction("Rate", new {VersID = post.VersID});
        }

        public PartialViewResult Reflection(int VersID)
        {
            RatingViewModel model = new RatingViewModel() {TaskVersion = db.getTaskVersion(VersID) };
            return PartialView(model);
        }

        public PartialViewResult Task(int VersID)
        {
            RatingViewModel model = db.getTaskRatings(VersID);
            return PartialView(model); 
        }

        public PartialViewResult Other(int VersID)
        {
            RatingViewModel model = db.getOtherRatings(VersID);
            return PartialView(model); 
        }

        [HttpPost]
        public ActionResult AddOther(RatingViewModel post)
        {
            CoreRating ratingToAdd;
            if (post.Rating.OtherCoreRatings != null)
            {
                int addindex = post.Rating.OtherCoreRatings.Count - 1;
                ratingToAdd = post.Rating.OtherCoreRatings[addindex];
            }
            else ratingToAdd = null;
            
            if (ratingToAdd != null && ratingToAdd.RatingID == 0 && ValidateCoreRating(ratingToAdd))
            {
                CompleteRating rating = new CompleteRating()
                {
                    OtherCoreRatings = new List<CoreRating>()
                };
                rating.OtherCoreRatings.Add(ratingToAdd); 
                db.saveTaskRating(rating, post.VersID);
            }

            RatingViewModel model = db.getOtherRatings(post.VersID);
            model.OtherVisible = true;
            return PartialView("Other", model); 
        }

        public PartialViewResult Impact(int VersID, bool ImpactVisible = false)
        {
            RatingViewModel model = db.getImpactRatings(VersID);
            model.ImpactVisible = ImpactVisible;
            return PartialView(model);
        }

        private bool ValidateCoreRating(CoreRating rating)
        {
            if (((rating.Cscore > 0 && rating.Cscore < 4) || rating.Cscore == null) && 
                ((rating.Sscore > 0 && rating.Sscore < 4) || rating.Sscore == null) &&
                ((rating.Pscore > 0 && rating.Pscore < 4) || rating.Pscore == null))            
                return true;
            else
                return false; 
        }

        public PartialViewResult Clear(int VersID, int RatingID, string Type)
        {
            if (VersID > 0 && (Type == "Task" || Type == "Other"))
                db.deleteTaskRating(RatingID);
            else if (VersID > 0 && Type == "Impact")
                db.deleteImpactRating(RatingID);
            switch (Type)
            {
                case "Task":
                    return PartialView("Task", db.getTaskRatings(VersID));
                case "Other":
                    return PartialView("Other", db.getOtherRatings(VersID));
                case "Impact":
                     RatingViewModel model = db.getImpactRatings(VersID);
                     model.ImpactVisible = false;
                     return PartialView("Impact", model);
                case "Default":
                    break;
            }
            return PartialView("Task", db.getTaskRatings(VersID));
        }
    }
}

LEDE.WebUI/Views/Rating/GetIndexData.cshtml
@using LEDE.Domain.Entities;
@model IEnumerable<TaskVersion>

@if (Model.Any())
{
    foreach (TaskVersion version in Model)
    {
        @Html.Hidden("VersID", version.VersID)
        <tr>
            <td>@version.Task.TaskCode: @version.Task.TaskName</td>
            <td> @version.Version</td>
            <td>@Html.ActionLink(version.Document.FileName, "Download", new { DocumentID = version.DocumentID })</td>
            <td>@version.Document.UploadDate</td>
            @{string feedbackText;}
            @if (version.FeedbackDoc != null)
            {
                feedbackText = "Replace Feedback";
                <td>@Html.ActionLink(version.FeedbackDoc.FileName, "Download", new { DocumentID = version.FeedbackDocID })</td>
                <td>@version.FeedbackDoc.UploadDate</td>
            }
            else
            {
                feedbackText = "Upload Feedback";
                <td>-</td>
                <td>-</td>
            }
            <td>
                @Html.ActionLink(feedbackText, "Upload", new
       {
           VersID = version.VersID,
           User = version.User.FirstName + " " +
               version.User.LastName,
           TaskName = version.Task.TaskName,
           SelectedUserID = version.UserID,
           Version = version.Version,
           returnUrl = "/Rating/Index?userID=" + version.UserID + "&ProgramCohortID=" + ViewBag.ProgramCohortID
       }, new
       {
           @class =
               "btn btn-default upload"
       })
        </td>
        <td>
            @if (version.TaskRatings.FirstOrDefault() == null)
            {
                @Html.ActionLink("Rate Now", "Rate", new { VersID = version.VersID }, new { @class = "btn btn-default" })
            }
            else
            {
                @Html.ActionLink("View Rating", "Rate", new { VersID = version.VersID }, new { @class = "btn btn-default" })
            }
        </td>
    </tr>
    }
}
else
{
    <tr>
        <td colspan="8">
            This Candidate Hasn't Submitted Any Assigments Yet. 
        </td>
    </tr>
}

LEDE.WebUI/Views/Rating/Index.cshtml
@using LEDE.Domain.Entities
@model RatingIndexModel
@{
    ViewBag.Title = "Feedback";
    AjaxOptions ajaxopts = new AjaxOptions
    {
        UpdateTargetId = "tbody",
        Url = Url.Action("GetIndexData"),
        LoadingElementId = "ajaxspinner"
    };
}
@section script{
<script src="~/Scripts/UploadPopup.js"></script>
    <script type="text/javascript">
        $(function () {
            $('input:submit').click(function () {
                $('#tbody').empty(); 
            });
        });
    </script>
}

@section css{
    <style>
        .spinnerplaceholder {
            text-align:center;
            margin-left:auto; margin-right:auto;
        }
        #ajaxspinner {
            display:none;
        }
    </style>
}
<div class="row page-header">
    <div class="col-md-3">
       <h2>Task Feedback</h2>
    </div>
    <div class="col-md-3">
        @using (Html.BeginForm())
        {
            @Html.DropDownListFor(x => x.SelectedCohortID, Model.Cohorts,
        new { @class = "form-control", onchange = "this.form.submit()" })
        }
    </div>
    <div class="col-md-5">
        @using (Ajax.BeginForm(ajaxopts))
        {
            @Html.Hidden("ProgramCohortID", Model.SelectedCohortID)
            @Html.DropDownListFor(x => x.SelectedUserID, Model.Candidates,
            new { @class = "form-control", onchange="$(this.form).submit();", style="display:inline;"})
        }
    </div>
</div>
    
<br />
<table class="table table-striped">
    <thead><tr><th>Task</th><th>Version</th><th>Document</th><th>Date Modified</th><th>Feedback Document</th><th>Date Modified</th><th></th><th></th></tr></thead>
    <tbody id="tbody">
        @Html.Action("GetIndexData", new { SelectedUserID = Model.SelectedUserID, ProgramCohortID = Model.SelectedCohortID })
    </tbody>
</table>
<div class="spinnerplaceholder"><img id="ajaxspinner" src="~/Images/ajax-loader.gif" /></div>

LEDE.WebUI/Views/Rating/Rate.cshtml
@using LEDE.Domain.Entities
@model RatingViewModel

@section script {
    <script src="~/Angular/angular.js"></script>
    <script src="~/Angular/angular-animate.js"></script>
    <script src="~/Angular/angular-resource.js"></script>
    <script src="~/Angular/app.js"></script>
    <script src="~/Angular/rate/rate.controller.js"></script>
    <script src="~/Angular/services/gradeService.js"></script>
    <script src="~/Angular/directives/coreRatingRow.js"></script>
    <script src="~/Angular/services/taskRating.js"></script>
    <script src="~/Angular/services/ratingResource.js"></script>
    <script src="~/Angular/services/taskVersionResource.js"></script>
    <script src="~/Angular/filters/seminarRating.js"></script>
    <script src="~/Scripts/UploadPopup.js"></script>
}
@section css {
    <link href="~/Angular/rating.css" type="text/css" rel="stylesheet" />
}

@if (ViewBag.InvalidAccessError == true)
{
    <p>Sorry, you don't have permission to access that page. <a href="/">Back to Home</a></p>
}
else
{
    <div class="page-header">
        <div class="row">
            <div class="col-md-9">
                <h2>Rate Task</h2>
                <h3>@Model.TaskVersion.Task.TaskName - @Model.TaskVersion.User.LastName, @Model.TaskVersion.User.FirstName</h3>
            </div>
            <div class="col-md-1">
                @using (Html.BeginForm("Header", "Rating", FormMethod.Post))
                {
                    @Html.DropDownListFor(x => x.VersID, Model.VersionDrop,
                    new { style = "width:75px", onchange = "this.form.submit();", @class = "form-control", id = "versionDrop" })
                }
            </div>
            <div class="col-md-2" style="text-align:right;">
                @Html.ActionLink("DL", "Download", new { DocumentID = Model.TaskVersion.DocumentID },
                new { @class = "btn btn-default", title = "Download Candidate Submission" })
                @Html.ActionLink("UL", "Upload", new
           {
               VersID = Model.TaskVersion.VersID,
               SelectedUserID =
                   Model.TaskVersion.UserID,
               User = Model.TaskVersion.User.FirstName + " " + Model.TaskVersion.User.LastName,
               TaskName = Model.TaskVersion.Task.TaskName,
               Version = Model.TaskVersion.Version,
               returnUrl = Request.Url.PathAndQuery
           },
           new { @class = "btn btn-default upload", title = "Upload Feedback For Submission" })
            </div>
        </div>
    </div>

    <div ng-app="facultyApp">
        <div ng-controller="RateCtrl" ng-switch="errorFetchingGrade">

            <img ng-switch-default class="grade-loading" src="~/Images/ajax-loader.gif" />
            <span ng-switch-when="true">Error Fetching Grade. Please reload and try again.</span>

            <div ng-switch-when="false">
                <span ng-show="UploadMessage !== undefined" class="upload-message">{{UploadMessage}}</span>

                <form name="gradeForm" novalidate>

                    <ng-form name="logForm" ng-if="grade.Log.IsExistingRating() === true" class="form-group row">
                        <label class="rating-label">
                            Number of Entries
                            <input class="form-control" type="number" ng-model="grade.Log.data.NumEntries" min="0" required integer />
                        </label>
                        <span class="rating-error" ng-show="logForm.$invalid">Please enter an integer number of hours</span>
                    </ng-form>

                    <ng-form name="reflectionForm" ng-if="grade.Reflection.IsExistingRating() === true" class="form-group row">
                        <label class="rating-label">
                            Number of Hours
                            <input class="form-control" type="number" ng-model="grade.Reflection.data.NumHours" min="0" required />
                        </label>
                        <span class="rating-error" ng-show="reflectionForm.$invalid">Please enter a number of hours</span>
                    </ng-form>

                    <ng-form name="seminarCoreForm" class="row">
                        <h3 class="rating-table-header">Seminar Core Ratings</h3>
                        <span class="rating-error" ng-show="seminarCoreForm.$invalid">Please enter an integer between 0 and 3</span>
                        <table class="table rating-table">
                            <tr>
                                <th>Core Topic</th>
                                <th>Conceptual</th>
                                <th>Strategic</th>
                                <th>Personal</th>
                                <th></th>
                            </tr>
                            <tr ng-repeat="rating in grade.CoreRatings| seminarRating:SeminarID" core-rating-row rating="rating"></tr>
                        </table>
                    </ng-form>

                    <ng-form name="otherCoreForm" class="row">
                        <div ng-switch="showOther" ng-click="showOther = !showOther" class="rating-toggle">
                            <h3 class="rating-table-header">Other Core Ratings</h3>
                            <span class="glyphicon glyphicon-collapse-up" ng-switch-when="true"></span>
                            <span class="glyphicon glyphicon-collapse-down" ng-switch-default></span>
                            <span class="rating-error" ng-show="otherCoreForm.$invalid">Please enter an integer between 0 and 3</span>
                        </div>
                        <table class="table rating-table">
                            <tr>
                                <th>Core Topic</th>
                                <th>Conceptual</th>
                                <th>Strategic</th>
                                <th>Personal</th>
                                <th></th>
                            </tr>
                            <tr ng-repeat="rating in grade.CoreRatings | otherRating:SeminarID:showOther" core-rating-row rating="rating"></tr>
                        </table>
                    </ng-form>

                    <ng-form name="impactForm" class="row">
                        <h3 class="rating-table-header">Impact Rating</h3>
                        <span class="rating-error" ng-show="impactForm.$invalid">Please enter an integer between 0 and 3</span>
                        <table class="table rating-table">
                            <tr>
                                <th>Structures & Operations</th>
                                <th>Professional Practices</th>
                                <th>Student Learning</th>
                                <th></th>
                            </tr>
                            <tr>
                                <td>
                                    <input type="number" ng-model="grade.ImpactRating.data.SScore" min="0" max="3" integer />
                                </td>
                                <td>
                                    <input type="number" ng-model="grade.ImpactRating.data.PScore" min="0" max="3" integer />
                                </td>
                                <td>
                                    <input type="number" ng-model="grade.ImpactRating.data.LScore" min="0" max="3" integer />
                                </td>
                                <td>
                                    <span class="glyphicon glyphicon-remove" ng-click="grade.ImpactRating.Clear()" ng-show="!grade.ImpactRating.IsEmpty()"></span>
                                </td>
                            </tr>
                        </table>
                    </ng-form>

                    <div class="rating-submit row">
                        <button class="btn-success" ng-click="SaveGrade()" ng-disabled="gradeForm.$invalid">Save</button>
                        <div class="rating-save-message">
                            <span ng-switch="errorSavingGrade">
                                <span ng-switch-when="false">Saved Successfully! Redirecting to Home Page.</span>
                                <span ng-switch-when="true">Failed To Save Rating. Please try again.</span>
                            </span>
                        </div>
                    </div>
                </form>
            </div>            
        </div>
    </div>

}

LEDE.WebUI/Views/Rating/Upload.cshtml
@using LEDE.Domain.Entities
@model int
@{
    AjaxOptions opts = new AjaxOptions()
    {
        Url = Url.Action("Upload", "Rating", new { SelectedUserID = ViewBag.SelectedUserID, VersID = Model, returnUrl = ViewBag.ReturnUrl }),
        UpdateTargetId = "upload-popup",
    };
}
<div id="upload-popup" class="white-popup" style="position: relative; background: #FFF; padding: 20px; width: auto; max-width: 750px; margin: 20px auto;">
    @if (Model == -1)
    {
        @ViewBag.Message
    }
    else
    {
        <h3>Upload Feedback</h3>
    <h4>@ViewBag.User - @ViewBag.TaskName (V@(ViewBag.Version))</h4>
    using(Html.BeginForm("Upload","Rating",new { SelectedUserID = ViewBag.SelectedUserID, VersID = Model, returnUrl = ViewBag.ReturnUrl },
        FormMethod.Post ,new { enctype = "multipart/form-data" })){
        <input type="file" name="file" style="display:inline;"/>
        <input type="submit" value="Submit" style="display:inline;" id="filesubmit"/>
    }
    }
</div>