LEDE.WebUI/Controllers/AdminController.cs
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity.Owin;
using LEDE.Domain.Concrete;
using LEDE.Domain.Entities;
using Microsoft.AspNet.Identity;
using System.Threading.Tasks;
using System.Linq; 
using LEDE.Domain.Abstract;
using System.Collections.Generic; 

namespace LEDE.WebUI.Controllers
{
    [Authorize(Roles="ECSEL Admin, LEDE Admin, Super Admin")]
    public class AdminController : Controller
    {
        private IUserRepository users;

        public AdminController(IUserRepository repo)
        {
            this.users = repo; 
        }

        public ActionResult Index(int? id)
        {
            IEnumerable<IndexModel> model = users.GetUsersWithRole();             

            return View(model);
        }

        public ActionResult Create()
        {
            CreateModel model = new CreateModel(){Roles = new SelectList(RoleManager.Roles, "Name", "Name")};
         
            return View(model); 
        }

        [HttpPost]
        public async Task<ActionResult> Create(CreateModel model)
        {
            if (ModelState.IsValid)
            {                
                User user = new User { UserName = model.UserName, FirstName = model.FirstName, 
                    LastName = model.LastName, UniversityID = model.UniversityID};
                IdentityResult result = await UserManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    await UserManager.AddToRoleAsync(user.Id, model.SelectedRole); 
                    return RedirectToAction("Index");
                }                    
                else
                    AddErrorsFromResult(result);
            }
            model.Roles = new SelectList(RoleManager.Roles, "Name", "Name"); 
            return View(model);
        }

        //[HttpPost]
        public async Task<ActionResult> Delete(int id)
        {
            User user = await UserManager.FindByIdAsync(id);
            if (user != null)
            {
                IdentityResult result = await UserManager.DeleteAsync(user);
                if (result.Succeeded)
                    return RedirectToAction("Index");
                else
                    return View("Error", result.Errors);
            }
            else
                return View("Error", new string[] { "User Not Found" });
        }

        public ActionResult Edit(int UserID)
        {
            EditModel model = new EditModel();
            model.User = UserManager.FindById(UserID); 
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(EditModel post)
        {
            EditModel editModel = post;
            User user = await UserManager.FindByIdAsync(editModel.User.Id);
            if (user != null)
            {
                users.Edit(editModel.User);      
                IdentityResult validPass = null;
                if (editModel.Password != string.Empty && editModel.Password != null)
                {
                    validPass
                        = await UserManager.PasswordValidator.ValidateAsync(editModel.Password);
                    if (validPass.Succeeded)
                    {
                        user.PasswordHash =
                            UserManager.PasswordHasher.HashPassword(editModel.Password);
                    }
                    else
                    {
                        AddErrorsFromResult(validPass);
                    }
                }
                if ((validPass == null) || (editModel.Password != string.Empty && validPass.Succeeded))
                {
                    return RedirectToAction("Index"); 
                }
            }
            else
            {
                ModelState.AddModelError("", "User Not Found");
            }
            return View(user);
                       
        }

        private void AddErrorsFromResult(IdentityResult result)
        {
            foreach (string error in result.Errors)
            {
                ModelState.AddModelError("", error);
            }
        }

        private AppUserManager UserManager
        {
            get
            {
                return HttpContext.GetOwinContext().GetUserManager<AppUserManager>();
            }
        }

        private AppRoleManager RoleManager
        {
            get
            {
                return HttpContext.GetOwinContext().GetUserManager<AppRoleManager>();
            }
        }
    }
}

LEDE.WebUI/Controllers/SetupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LEDE.Domain.Entities;
using LEDE.Domain.Abstract;

namespace LEDE.WebUI.Controllers
{
    [Authorize(Roles="ECSEL Admin, Super Admin, LEDE Admin")]
    public class SetupController : Controller
    {
        private IEnrollmentRepository db;

        public SetupController(IEnrollmentRepository repo)
        {
            this.db = repo;
        }

        public ActionResult Programs(string DeleteEntity, int DeleteID = 0, int SelectedItemID = 0)
        {
            //Handle Deletion for non-ajax requests 
            if (DeleteEntity != null)
            {
                if (DeleteEntity == "Cohort")
                    db.deleteProgramCohort(DeleteID);
                else if (DeleteEntity == "Seminar")
                    db.deleteProgramSeminar(DeleteID); 
            }

            ListViewModel model = new ParentViewModel()
            {
                Items = db.getPrograms().Select(p => new ListItem() {Id = p.ProgramID, Name = p.ProgramTitle }),
                editAction = "EditProgram",
                Entity = "Program",
                ChildEntities = new List<ChildEntity>()
                {
                    new ChildEntity(){Entity = "Cohort", Action="ProgramCohorts"},
                    new ChildEntity(){Entity = "Seminar", Action="ProgramSeminars"}
                },
                SelectedItemID = SelectedItemID, 
            };
            return View("ListPanel",model);
        }
        

        public ActionResult EditProgram(int Id)
        {
            Program model = db.getPrograms().Single(p => p.ProgramID == Id); 
            return View(model); 
        }

        [HttpPost]
        public ActionResult EditProgram(Program post)
        {
            db.editProgram(post);
            return RedirectToAction("Programs"); 
        }

        public PartialViewResult ProgramItems(int ParentID, string delete, int Id = 0)
        {
            if (delete == "Cohort")
                db.deleteProgramCohort(Id);
            else if (delete == "Seminar")
                db.deleteProgramSeminar(Id);

            ListViewModel cohorts = null;
            ListViewModel seminars = null; 

            if(delete == "Cohort" || delete == null)
            {
                cohorts = new ListViewModel()
                {
                    Items = db.getCohorts().Where(pc => pc.ProgramID == ParentID).
                    Select(pc => new ListItem() { Id = pc.ProgramCohortID, Name = pc.Program.ProgramTitle + " " + pc.AcademicYear }),
                    Entity = "Cohort",
                    createAction = "createProgramCohort",
                    deleteAction = "ProgramItems",
                    editAction = "createProgramCohort"
                };
            }
            
            if(delete == "Seminar" || delete == null)
            {
                seminars = new ListViewModel()
                {
                    Items = db.getSeminars().Where(s => s.ProgramID == ParentID).
                    Select(s => new ListItem() { Id = s.SeminarID, Name = s.SeminarTitle }),
                    Entity = "Seminar",
                    createAction = "createProgramSeminar",
                    deleteAction = "ProgramItems",
                    editAction = "createProgramSeminar",
                };         
            }              
            
            ChildViewModel model = new ChildViewModel()
            {
                ParentID = ParentID,
                Items = new List<ListViewModel>() { cohorts, seminars }
            };

            return PartialView("ChildPanel", model);
        }        

        public ActionResult createProgramCohort(int Id, int? EditID, string mode="Create")
        {
            ViewBag.mode = mode;
            ProgramCohort model;
            if (EditID != null)
                model = db.getCohorts().Single(c => c.ProgramCohortID == EditID);
            else
                model = new ProgramCohort() { ProgramID = Id };

            return View(model);
        }

        [HttpPost]
        public ActionResult createProgramCohort(ProgramCohort post)
        {
            if (post.ProgramCohortID > 0)
                db.editCohort(post); 
            else
                db.createProgramCohort(post);
            return RedirectToAction("Programs", new {SelectedItemID = post.ProgramID});
        }       

        public ActionResult createProgramSeminar(int Id, int? EditID, string mode = "Create")
        {
            ViewBag.mode = mode;
            Seminar model;
            if (EditID != null)
            {
                model = db.getSeminars().Single(s => s.SeminarID == Id);
            }
            else
            {
                model = new Seminar() { ProgramID = Id };
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult createProgramSeminar(Seminar post)
        {
            if (post.SeminarID > 0)
                db.editSeminar(post);
            else
                db.createProgramSeminar(post);
            return RedirectToAction("Programs", new { SelectedItemID = post.ProgramID }); 
        }

/////////////////////////////////////////////////
        public ActionResult Seminars(string DeleteEntity, int DeleteID = 0, int SelectedItemID = 0)
        {
            //Handle Deletion for non-ajax requests 
            if (DeleteEntity != null)
            {
                if (DeleteEntity == "CoreTopic")
                    db.deleteSeminarCoreTopic(DeleteID);
                else if (DeleteEntity == "Task")
                    db.deleteSeminarTask(DeleteID);
            }

            ListViewModel model = new ParentViewModel()
            {
                Items = db.getSeminars().Select(s => new ListItem() { Id = s.SeminarID, Name = s.Program.ProgramTitle + "-" + s.SeminarTitle }).
                OrderBy(s=> s.Name),
                editAction = "EditSeminar",
                Entity = "Seminar",
                ChildEntities = new List<ChildEntity>()
                {
                    new ChildEntity(){Entity = "CoreTopic", Action="SeminarCoreTopics"},
                    new ChildEntity(){Entity = "Task", Action="SeminarTasks"}
                },
                SelectedItemID = SelectedItemID,
            };
            return View("ListPanel", model);
        }


        public ActionResult EditSeminar(int Id)
        {
            Seminar model = db.getSeminars().Single(s => s.SeminarID == Id);
            return View(model);
        }

        [HttpPost]
        public ActionResult EditSeminar(Seminar post)
        {
            db.editSeminar(post);
            return RedirectToAction("Seminars");
        }

        public PartialViewResult SeminarItems(int ParentID, string delete, int Id = 0)
        {
            if (delete == "CoreTopic")
                db.deleteSeminarCoreTopic(Id);
            else if (delete == "Task")
                db.deleteSeminarTask(Id);

            ListViewModel coretopics = null;
            ListViewModel tasks = null;

            if (delete == "CoreTopic" || delete == null)
            {
                coretopics = new ListViewModel()
                {
                    Items = db.getCoreTopics().Where(ct => ct.SeminarID == ParentID).
                    Select(ct => new ListItem() { Id = ct.CoreTopicID, Name = ct.CoreTopicNum + " " + ct.CoreTopicDesc}),
                    Entity = "CoreTopic",
                    createAction = "createSeminarCoreTopic",
                    deleteAction = "SeminarItems",
                    editAction = "editCoreTopic"
                };
            }

            if (delete == "Task" || delete == null)
            {
                tasks = new ListViewModel()
                {
                    Items = db.getTasks().Where(t => t.SeminarID == ParentID).
                    Select(t => new ListItem() { Id = t.TaskID, Name = t.TaskCode + ": " + t.TaskName }),
                    Entity = "Task",
                    createAction = "createSeminarTask",
                    deleteAction = "SeminarItems",
                    editAction = "editTask",
                };
            }

            ChildViewModel model = new ChildViewModel()
            {
                ParentID = ParentID,
                Items = new List<ListViewModel>() { coretopics, tasks }
            };

            return PartialView("ChildPanel", model);
        }

        public ActionResult createSeminarCoreTopic(int Id)
        {
            CoreTopic model = new CoreTopic() { SeminarID = Id, ModifyDate = DateTime.Now };
            return View(model);
        }

        [HttpPost]
        public ActionResult createSeminarCoreTopic(CoreTopic post)
        {
            if (post.CoreTopicID > 0)
                db.editSeminarCoretopic(post);
            else
                db.createSeminarCoreTopic(post);
            return RedirectToAction("Seminars", new { SelectedItemID = post.SeminarID });
        }

        public ActionResult createSeminarTask(int Id)
        {
            Task model = new Task() { SeminarID = Id };
            ViewBag.TaskTypeID = new SelectList(db.getTaskTypes(),"TaskTypeID","TaskTypeDescription");
            return View(model);
        }

        [HttpPost]
        public ActionResult createSeminarTask(Task post)
        {
            if (post.TaskID > 0)
                db.editSeminarTask(post);
            else
                db.createSeminarTask(post);

            return RedirectToAction("Seminars", new { SelectedItemID = post.SeminarID });
        }

        public ActionResult editTask(int Id)
        {
            Task model = db.getTasks().Single(t => t.TaskID == Id);
            ViewBag.TaskTypeID = new SelectList(db.getTaskTypes(), "TaskTypeID", "TaskTypeDescription");
            return View("createSeminarTask",model); 
        }

LEDE.WebUI/Controllers/SummaryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LEDE.Domain.Entities;
using LEDE.Domain.Concrete;
using LEDE.Domain.Abstract;
using Microsoft.AspNet.Identity;

namespace LEDE.WebUI.Controllers
{
    //[Authorize(Roles = "Faculty")]
    public class SummaryController : Controller
    {
        private ISummaryRepository db;
        private IPercentageCalculator Calculator;

        public SummaryController(ISummaryRepository repo, IPercentageCalculator calc)
        {
            this.db = repo;
            this.Calculator = calc;
        }

        [AllowAnonymous]
        public ActionResult Seminar(SeminarSummary summary)
        {
            //get dropdown sorted
            SelectList programCohorts = new SelectList(db.getCohorts(), "ProgramCohortID", "Program.ProgramTitle");
            int selectedCohortID = summary.SelectedCohortID == 0 ? Convert.ToInt32(programCohorts.First().Value) : summary.SelectedCohortID;

            //initialize page model 
            SeminarSummary model = db.getCohortTotals(1, 1);
            model.SelectedCohortID = selectedCohortID;
            Calculator.CalculateSeminarPercentages(model);
            model.ProgramCohorts = programCohorts;

            return View(model);
        }

        public ActionResult Student(int UserID, int ProgramCohortID)
        {            
            StudentSummary model = db.getStudentTotals(ProgramCohortID, UserID);
            Calculator.CalculateStudentPercentages(model);
            return View(model);
        }

        public ActionResult Summary(SummaryModel post)
        {
            int? SelectedCohortID = post.ProgramCohortID == 0 ? (int?)null : post.ProgramCohortID;
            SummaryModel model = db.getSummaryCohorts(Convert.ToInt32(User.Identity.GetUserId()), SelectedCohortID);
            db.getSummaryCandidates(model); 

            return View(model); 
        }

        public PartialViewResult SummarySpreadsheet(int ProgramCohortID, int UserID)
        {
            SpreadsheetModel model = db.getSpreadsheetTable(ProgramCohortID, UserID); 
            return PartialView(model); 
        }
    }
}

LEDE.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <base href="/" />
    <title>LEDE & ECSEL</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/Header.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/magnific-popup.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <style>
        container {
            padding-top: 10px;
        }

        .jumbotron {
            margin-top: 10px;
        }

        .validation-summary-errors {
            color: #f00;
        }
    </style>

    @RenderSection("css", false)

</head>
<body>
    <nav class="mainnav navbar-fixed-top">
        <div class="navbar">
            <div class="container">
                <div class="navbar-header navbar-collapse">
                    <span class="navbar-brand navbartext">LEDE & ECSEL</span>
                </div>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
        <div class="navbar navbar-default" role="navigation">
            <div class="container">
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        @if (User.IsInRole("Candidate"))
                        {
                            <li>@Html.ActionLink("Tasks", "Summary", "Candidate")</li>
                            <li>@Html.ActionLink("Upload", "Index", "Candidate")</li>
                            <li>@Html.ActionLink("Summary", "Student", "Report")</li>

                        }
                        else if (User.IsInRole("Faculty"))
                        {
                            <li>@Html.ActionLink("Feedback", "Index", "Rating")</li>
                            <li>@Html.ActionLink("Submissions", "Summary", "Faculty")</li>
                            <li>@Html.ActionLink("Graphs", "Seminar", "Report")</li>
                        }
                        else if (User.IsInRole("ECSEL Admin") || User.IsInRole("LEDE Admin") || User.IsInRole("Super Admin"))
                        {
                            <li>@Html.ActionLink("Users", "Index", "Admin")</li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Reports<span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li>@Html.ActionLink("Graphs", "Seminar", "Report")</li>
                                    <li>@Html.ActionLink("Summary", "Summary", "Report")</li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Setup<span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        @Html.ActionLink("Programs", "Programs", "Setup")
                                    </li>
                                    <li>
                                        @Html.ActionLink("Cohorts", "Index", "Setup")
                                    </li>
                                    <li>
                                        @Html.ActionLink("Seminars", "Seminars", "Setup")
                                    </li>
                                </ul>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </div>
    </nav>
    <div class="container">
        @RenderBody()
    </div>
    <script src="~/Scripts/jquery-2.1.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery.magnific-popup.min.js"></script>

    @RenderSection("script", false)
</body>
</html>